apiVersion: apps/v1
kind: Deployment
metadata:
    name: orderapp
    labels:
        app: orderapp
    annotations:
        kubectl.kubernetes.io/change-cause: "My second annotation, switching to version 1.4"
spec:
    replicas: 3
    selector:
        matchLabels:
            app: orderapp-deployment
    template:
        metadata:
            labels:
                app: orderapp-deployment
        spec:
            containers:
                - name: orderapp-container
                  image: sudeev123/orderapp:1.4
                  ports:
                      - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
    name: orderapp-service
spec:
    selector:
        app: orderapp-deployment
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
          nodePort: 30001

    type: NodePort